### ISSUE TITLE
'failed to find top-level export `initSync`'

### ISSUE THREAD

**Issue by Carlrs** [wilsonzlin/minify-js#7] opened 2023-01-12 23:54 UTC
Having trouble parsing wasm-bindgen output again, this time it's about exports. File in question:

https://gist.github.com/Carlrs/67035c2639f0df5d4eca13e47f64a2ea

**Comment by wilsonzlin** [comment] 2023-01-31 09:42
I just had a look again and it appears to be working. It only fails if I choose `TopLevelMode::Global`, which is incorrect as there's an `export`. Are you able to reproduce the issue with `TopLevelMode::Module`?

The error is caused by the fact that in global mode, top-level variables are not actually inside any scope. I'll look at improving the error case and avoiding a panic for this situation.

**Comment by wilsonzlin** [comment] 2023-01-31 12:07
Closing in favour of #9.

**Closed by wilsonzlin** 2023-01-31 12:07 UTC
